#!/bin/bash

docker build -t rhel7toolchain - <<EOF
FROM centos:7
# Perfomance: fix Delta RPMs disabled because /usr/bin/applydeltarpm not installed
RUN yum -y install deltarpm
# Perfomance: workaround https://github.com/docker/buildx/issues/379
RUN echo "ulimit is $(ulimit -n)" && ulimit -n 1024000 && yum -y install git flex bison make gcc findutils openssl-devel bc diffutils elfutils elfutils-devel perl vim openssl dwarves sshpass openssh-clients
RUN yum clean all
RUN git clone https://github.com/Snorch/ovzhelpers.git && cd ovzhelpers && ./install.sh
EOF

docker run -it --rm --network=host -v $PWD:/vzkernel rhel7toolchain bash -i -c "cd /vzkernel && kmake $1 && echo '>>> SUCCESS <<<'"
