#!/bin/bash

FEDORA_VERSION="41"
DNF_DEPS=""

DNF_DEPS+="kmod bash coreutils tar git which "
DNF_DEPS+="bzip2 xz findutils gzip m4 perl make diffutils gawk "
DNF_DEPS+="gcc binutils redhat-rpm-config hmaccalc bison flex gcc-c++ "
DNF_DEPS+="net-tools hostname bc "
DNF_DEPS+="elfutils elfutils-devel "
DNF_DEPS+="dwarves "
DNF_DEPS+="python3-devel "
DNF_DEPS+="gcc-plugin-devel "
DNF_DEPS+="kernel-rpm-macros "
DNF_DEPS+="rsync "
DNF_DEPS+="glibc-static "
DNF_DEPS+="libbpf-devel "
DNF_DEPS+="libnl3-devel "
DNF_DEPS+="openssl openssl-devel openssl-devel-engine "
DNF_DEPS+="lld "
DNF_DEPS+="rpm-build "
DNF_DEPS+="cpio xz "
DNF_DEPS+="ccache "

usage() {
    cat >&2 <<'USAGE'
Usage:
  build-kernel [kmake-suffix]    Run 'kmake [suffix]' in the build container
  build-kernel -c "command"      Run a custom command in the build container
  build-kernel < script.sh       Read commands to run from stdin
  build-kernel <<'EOF'           Read commands from a heredoc
    cmd1
    cmd2
  EOF

Options:
  -c CMD   Run CMD inside the build container instead of kmake
  -v VER   Specify docker image version for Fedora
  -h       Show this help
USAGE
}

CUSTOM_CMD=""
while getopts "v:c:h" opt; do
    case "$opt" in
        c) CUSTOM_CMD="$OPTARG" ;;
        v) FEDORA_VERSION="$OPTARG" ;;
        h) usage; exit 0 ;;
        *) usage; exit 1 ;;
    esac
done
shift $((OPTIND - 1))

if [ -n "$CUSTOM_CMD" ] && [ "$#" -gt 0 ]; then
    echo "build-kernel: -c cannot be combined with positional arguments" >&2
    exit 1
fi

SUDO="sudo"
if [ "$(id -u)" -eq 0 ] || id -nG | tr ' ' '\n' | grep -qx docker; then
    SUDO=""
fi

$SUDO docker build -t kernel-build-toolchain:${FEDORA_VERSION} - <<EOF
FROM fedora:${FEDORA_VERSION}
RUN dnf -y install $DNF_DEPS
RUN yum clean all
RUN git clone https://github.com/Snorch/ovzhelpers.git && cd ovzhelpers && ./install.sh
RUN echo "PATH=\"/root/bin:/usr/lib64/ccache:\$PATH\"" >> /root/.bashrc
EOF

if [ ! -e ~/.ccache ]; then
    mkdir -p ~/.ccache
    echo "max_size=120G" > ~/.ccache/ccache.conf
    echo ">>> Created ccache directory at ~/.ccache <<<"
fi

# Pick the command to run inside the container:
#   -c CMD    -> run CMD
#   stdin     -> run whatever was piped/heredoc'd in
#   otherwise -> default kmake invocation (interactive)
if [ -n "$CUSTOM_CMD" ]; then
    BUILD_CMD="$CUSTOM_CMD"
    HAVE_BUILD_CMD=1
elif [ ! -t 0 ]; then
    BUILD_CMD="$(cat)"
    HAVE_BUILD_CMD=1
else
    HAVE_BUILD_CMD=0
fi

if [ "$HAVE_BUILD_CMD" = "1" ]; then
    {
        echo 'set -e'
        echo 'export PATH="/root/bin:/usr/lib64/ccache:$PATH"'
        echo 'cd /kernel'
        printf '%s\n' "$BUILD_CMD"
        echo 'echo ">>> SUCCESS <<<"'
    } | $SUDO docker run -i --rm --network=host \
        -v $PWD:/kernel \
        -v ~/.ccache:/root/.ccache \
        kernel-build-toolchain:${FEDORA_VERSION} \
        bash
else
    $SUDO docker run -it --rm --network=host \
        -v $PWD:/kernel \
        -v ~/.ccache:/root/.ccache \
        kernel-build-toolchain:${FEDORA_VERSION} \
        bash -i -c "cd /kernel && kmake $1 && echo '>>> SUCCESS <<<'"
fi
