#!/bin/bash

docker build -t rhel9toolchain - <<EOF
FROM fedora:39
RUN dnf -y install kmod bash coreutils tar git which
RUN dnf -y install bzip2 xz findutils gzip m4 perl make diffutils gawk
RUN dnf -y install gcc binutils redhat-rpm-config hmaccalc bison flex gcc-c++
RUN dnf -y install net-tools hostname bc
RUN dnf -y install elfutils elfutils-devel
RUN dnf -y install dwarves
RUN dnf -y install python3-devel
RUN dnf -y install gcc-plugin-devel
RUN dnf -y install kernel-rpm-macros
RUN dnf -y install rsync
RUN dnf -y install glibc-static
RUN dnf -y install libbpf-devel
RUN dnf -y install libnl3-devel
RUN dnf -y install openssl openssl-devel
RUN dnf -y install lld
RUN dnf -y install rpm-build
RUN dnf -y install cpio xz
RUN yum clean all
RUN git clone https://github.com/Snorch/ovzhelpers.git && cd ovzhelpers && ./install.sh
EOF

docker run -it --rm --network=host -v $PWD:/vzkernel rhel9toolchain bash -i -c "cd /vzkernel && kmake && echo '>>> SUCCESS <<<'"
