#!/bin/bash

FEDORA_VERSION="latest"
DNF_DEPS=""

DNF_DEPS+="kmod bash coreutils tar git which "
DNF_DEPS+="bzip2 xz findutils gzip m4 perl make diffutils gawk "
DNF_DEPS+="gcc binutils redhat-rpm-config hmaccalc bison flex gcc-c++ "
DNF_DEPS+="net-tools hostname bc "
DNF_DEPS+="elfutils elfutils-devel "
DNF_DEPS+="dwarves "
DNF_DEPS+="python3-devel "
DNF_DEPS+="gcc-plugin-devel "
DNF_DEPS+="kernel-rpm-macros "
DNF_DEPS+="rsync "
DNF_DEPS+="glibc-static "
DNF_DEPS+="libbpf-devel "
DNF_DEPS+="libnl3-devel "
DNF_DEPS+="openssl openssl-devel openssl-devel-engine "
DNF_DEPS+="lld "
DNF_DEPS+="rpm-build "
DNF_DEPS+="cpio xz "
DNF_DEPS+="ccache "

KERNEL_VERSION="$(make -s kernelversion | cut -d- -f1)"
if [ "$(printf '%s\n5.14.0\n' "$KERNEL_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
	FEDORA_VERSION="41"
fi

sudo docker build -t kernel-build-toolchain:${FEDORA_VERSION} - <<EOF
FROM fedora:${FEDORA_VERSION}
RUN dnf -y install $DNF_DEPS
RUN yum clean all
RUN git clone https://github.com/Snorch/ovzhelpers.git && cd ovzhelpers && ./install.sh
RUN echo "PATH=\"/root/bin:/usr/lib64/ccache:\$PATH\"" >> /root/.bashrc
EOF

if [ ! -e ~/.ccache ]; then
    mkdir -p ~/.ccache
    echo "max_size=120G" > ~/.ccache/ccache.conf
    echo ">>> Created ccache directory at ~/.ccache <<<"
fi

sudo docker run -it --rm --network=host \
    -v $PWD:/kernel \
    -v ~/.ccache:/root/.ccache \
    kernel-build-toolchain:${FEDORA_VERSION} \
    bash -i -c "cd /kernel && kmake $1 && echo '>>> SUCCESS <<<'"
