#!/bin/bash

# Append "-kmake" to kernel build name to indicate that it's ours

SUBNAME="-${1:-kmake}"
./scripts/config --set-str CONFIG_LOCALVERSION "$SUBNAME"

# Makes the kernel and strips debuginfo for faster install and smaller initramfs

NTHREADS=$(($(nproc)+1))
make -j$NTHREADS && modstrip
